// <auto-generated />
using System;
using LinguaFlame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguaFlame.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503155220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LinguaFlame.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinguaFlame.Api.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedGrammarIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveMissedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreezesAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreezesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastActiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFreezeDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnedWordIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalExams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("LinguaFlame.Api.Models.UserProgress", b =>
                {
                    b.HasOne("LinguaFlame.Api.Models.User", "User")
                        .WithOne("Progress")
                        .HasForeignKey("LinguaFlame.Api.Models.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinguaFlame.Api.Models.User", b =>
                {
                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
